<?php

namespace ContainerUBso9xU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RoE6PmcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.roE6Pmc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.roE6Pmc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'couponRepository' => ['privates', 'App\\Repository\\CouponRepository', 'getCouponRepositoryService', true],
            'dto' => ['privates', 'App\\Dto\\PurchaseDto', 'getPurchaseDtoService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'purchaseService' => ['privates', 'App\\Service\\PurchaseService', 'getPurchaseServiceService', true],
        ], [
            'couponRepository' => '?',
            'dto' => 'App\\Dto\\PurchaseDto',
            'productRepository' => '?',
            'purchaseService' => 'App\\Service\\PurchaseService',
        ]);
    }
}
