<?php

namespace ContainerUBso9xU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZQAhSVRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZQAhSVR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZQAhSVR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\PurchaseController::calculatePrice' => ['privates', '.service_locator.ll1zf7c', 'get_ServiceLocator_Ll1zf7cService', true],
            'App\\Controller\\PurchaseController::index' => ['privates', '.service_locator.roE6Pmc', 'get_ServiceLocator_RoE6PmcService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PurchaseController:calculatePrice' => ['privates', '.service_locator.ll1zf7c', 'get_ServiceLocator_Ll1zf7cService', true],
            'App\\Controller\\PurchaseController:index' => ['privates', '.service_locator.roE6Pmc', 'get_ServiceLocator_RoE6PmcService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PurchaseController::calculatePrice' => '?',
            'App\\Controller\\PurchaseController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PurchaseController:calculatePrice' => '?',
            'App\\Controller\\PurchaseController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
