<?php

namespace ContainerUBso9xU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\BaseDto' shared autowired service.
     *
     * @return \App\Dto\BaseDto
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Dto/BaseDto.php';

        return $container->privates['App\\Dto\\BaseDto'] = new \App\Dto\BaseDto();
    }
}
