<?php

namespace ContainerUBso9xU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\PurchaseDto' shared autowired service.
     *
     * @return \App\Dto\PurchaseDto
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Dto/BaseDto.php';
        include_once \dirname(__DIR__, 4).'/src/Dto/PurchaseDto.php';

        return $container->privates['App\\Dto\\PurchaseDto'] = new \App\Dto\PurchaseDto();
    }
}
