<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUBso9xU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUBso9xU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUBso9xU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUBso9xU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUBso9xU\App_KernelDevDebugContainer([
    'container.build_hash' => 'UBso9xU',
    'container.build_id' => '7eee9d60',
    'container.build_time' => 1772455775,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUBso9xU');
