<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'purchase' => [[], ['_controller' => 'App\\Controller\\PurchaseController::index'], [], [['text', '/purchase']], [], [], []],
    'calculate-price' => [[], ['_controller' => 'App\\Controller\\PurchaseController::calculatePrice'], [], [['text', '/calculate-price']], [], [], []],
    'App\Controller\PurchaseController::index' => [[], ['_controller' => 'App\\Controller\\PurchaseController::index'], [], [['text', '/purchase']], [], [], []],
    'App\Controller\PurchaseController::calculatePrice' => [[], ['_controller' => 'App\\Controller\\PurchaseController::calculatePrice'], [], [['text', '/calculate-price']], [], [], []],
];
